language: php

php:
  - '7.4'

os: linux

dist: focal

cache:
  directories:
    - $HOME/.composer/cache

install:
  - pecl install ds
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - composer validate --strict
  - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml

after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

notifications:
  email:
    recipients:
      - mike@solovjov.net
    on_success: never
    on_failure: always

addons:
  code_climate:
    repo_token:
      secure: "ZrCH/eEowUIn8SyQRt8l3u5mHv36NzCxOfdo2iaunHwsved+z/b//fbAdbuYX20tGoDt/1v0no+LZH7PYOR/s10YX7UDMKdOqaQxvnW0fQQLcHj5LuQV/MeGuYFFiF+isgrzak9hdcAVGnt78Pwbt6E2GeplCuiOfv4taDVvoQlfmsfzBpZsZvGDYbXTkycmQeCQ8CXdTcsQtwAouXK3v7luSZ6tiI3bkkEWM133bCKxqTUTYVptH38ilIXSKh8eWY1pnrF1gKEC6cVzQWmE/tRJ7mjQ72jvJCGKATl9uN1P9jCYlIjRQrEHfcmtQF2os643ex7E7d/ldEYhbG1n+kaqGH/XgecZ8DwFdGMT9+06aEmySQ46EoSANIj8XHpTz4eHgKpF+YRqtetkGd7cR/Oj3hXXN5Oep/3wvWrQaiJNhaOPpl6EHPw0ydwuabOMPjQtV8Rn8hIJTzt6vZi3Ou2ibAa4glVzjuD3fXMn8WRLZAQLG05kSPtRrUqp/RVXZ0KY4Aq/L++rC3oHR+5Jpwq9h0RWwCQD2r9hkm8XJ/QJmr/64DGx9EYkHcWzU8jh2atCP/5CNblJxlrjYfxLQmhRLY9mFotXaz8ZfYLaXRGXeyW6BCyVg8Z3a6oOJWnr64KSJymiUm12KP9npDr3J32ePPnjI7T3AJ5Q21Az8Ww="
